
# Boost

if( WIN32 AND NOT BOOST_ROOT )
	SET (BOOST_ROOT ${BOOST_ROOT} CACHE STRING "Set the value of BOOST_ROOT to point to the root folder of your boost install." FORCE)
    MESSAGE( WARNING "Please set the BOOST_ROOT variable." )
endif( WIN32 AND NOT BOOST_ROOT )

set(Boost_ADDITIONAL_VERSIONS "1.47" "1.47.0")
#set(Boost_DEBUG ON)
set(Boost_USE_STATIC_LIBS       OFF)
set(Boost_USE_MULTITHREADED      ON)
set(Boost_USE_STATIC_RUNTIME    OFF)

FIND_PACKAGE(Boost 1.47.0 COMPONENTS date_time regex filesystem system)

FIND_PACKAGE(OpenCV REQUIRED)

# OpenEXR

SET(OPENEXR_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/depends/openexr/include/"  )

SET(OPENEXR_LIBRARY_ILMIMF_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Debug/IlmImf_d.lib" )
SET(OPENEXR_LIBRARY_ILMIMF_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Release/IlmImf.lib" )
SET(OPENEXR_LIBRARY_ILMTHREAD_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Debug/IlmThread_d.lib" )
SET(OPENEXR_LIBRARY_ILMTHREAD_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Release/ilmThread.lib" )
SET(OPENEXR_LIBRARY_IEX_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Debug/Iex_d.lib" )
SET(OPENEXR_LIBRARY_IEX_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Release/Iex.lib" )
SET(OPENEXR_LIBRARY_HALF_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Debug/Half_d.lib" )
SET(OPENEXR_LIBRARY_HALF_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Release/Half.lib" )
SET(OPENEXR_LIBRARY_IMATH_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Debug/Imath_d.lib" )
SET(OPENEXR_LIBRARY_IMATH_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/lib/Release/Imath.lib" )

SET(OPENEXR_DLL_ILMIMF_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Debug/IlmImf_d.dll" )
SET(OPENEXR_DLL_ILMIMF_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Release/IlmImf.dll" )
SET(OPENEXR_DLL_ILMTHREAD_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Debug/IlmThread_d.dll" )
SET(OPENEXR_DLL_ILMTHREAD_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Release/ilmThread.dll" )
SET(OPENEXR_DLL_IEX_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Debug/Iex_d.dll" )
SET(OPENEXR_DLL_IEX_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Release/Iex.dll" )
SET(OPENEXR_DLL_HALF_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Debug/Half_d.dll" )
SET(OPENEXR_DLL_HALF_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Release/Half.dll" )
SET(OPENEXR_DLL_IMATH_DEBUG "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Debug/Imath_d.dll" )
SET(OPENEXR_DLL_IMATH_RELEASE "${CMAKE_SOURCE_DIR}/depends/openexr/bin/Release/Imath.dll" )

SET(OPENEXR_LIBRARIES_DEBUG 
	debug ${OPENEXR_LIBRARY_ILMIMF_DEBUG} 
	debug ${OPENEXR_LIBRARY_ILMTHREAD_DEBUG} 
	debug ${OPENEXR_LIBRARY_IEX_DEBUG}	
	debug ${OPENEXR_LIBRARY_HALF_DEBUG} 
	debug ${OPENEXR_LIBRARY_IMATH_DEBUG} 
	debug ${OPENEXR_LIBRARY_ILMIMF_DEBUG} 
)
SET(OPENEXR_LIBRARIES_RELEASE 
	optimized ${OPENEXR_LIBRARY_ILMIMF_RELEASE} 
	optimized ${OPENEXR_LIBRARY_ILMTHREAD_RELEASE} 
	optimized ${OPENEXR_LIBRARY_IEX_RELEASE} 
	optimized ${OPENEXR_LIBRARY_HALF_RELEASE} 
	optimized ${OPENEXR_LIBRARY_IMATH_RELEASE} 
	optimized ${OPENEXR_LIBRARY_ILMIMF_RELEASE}
)

SET(OPENEXR_LIBRARIES ${OPENEXR_LIBRARIES_DEBUG} ${OPENEXR_LIBRARIES_RELEASE})

SET(OPENEXR_DLLS_DEBUG 
	${OPENEXR_DLL_ILMIMF_DEBUG} 
	${OPENEXR_DLL_ILMTHREAD_DEBUG}
	${OPENEXR_DLL_IEX_DEBUG}
	${OPENEXR_DLL_HALF_DEBUG}
	${OPENEXR_DLL_IMATH_DEBUG}
	${OPENEXR_DLL_ILMIMF_DEBUG}
)

SET(OPENEXR_DLLS_RELEASE 
	${OPENEXR_DLL_ILMIMF_RELEASE} 
	${OPENEXR_DLL_ILMTHREAD_RELEASE}
	${OPENEXR_DLL_IEX_RELEASE}
	${OPENEXR_DLL_HALF_RELEASE}
	${OPENEXR_DLL_IMATH_RELEASE}
	${OPENEXR_DLL_ILMIMF_RELEASE}
)

SET(OPENEXR_DLLS ${OPENEXR_DLLS_DEBUG} ${OPENEXR_DLLS_RELEASE} )

MARK_AS_ADVANCED(OPENEXR_INCLUDE_DIR OPENEXR_LIBRARIES OPENEXR_DLLS )


